#!/bin/sh

# This script lives on the node.x install directory which should be on the users PATH
# It is called like groovy e.g. nodex-groovy -cp "somepath" myScript

# We need to figure out what this directory is relative to wherever this is called from. Remember this dir is on the path
# so this script can be called from anywhere

PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

DIRNAME=`dirname "$PRG"`

EXTRA_CLASSPATH="-cp $DIRNAME/../lib/java/node.x.jar:$DIRNAME/../lib/java/netty.jar:$DIRNAME/../lib/java/high-scale-lib.jar"

# We need to append the EXTRA_CLASSPATH to any classpath specified on the command line

NEW_ARGS=
APPEND_CP=false
DISCARD_ARG=false
for arg in "$@"
do
  if $APPEND_CP ; then
    EXTRA_CLASSPATH=$EXTRA_CLASSPATH:$arg
    APPEND_CP=false
    DISCARD_ARG=true
  fi
  if [ $arg = "-cp" ] || [ $arg = "-classpath" ]; then
    APPEND_CP=true
    DISCARD_ARG=true
  fi
  
  if ! $DISCARD_ARG ; then
    NEW_ARGS=$NEW_ARGS" "$arg
  fi
  DISCARD_ARG=false
done

groovy $EXTRA_CLASSPATH $DIRNAME/gnodex $NEW_ARGS
